server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://118.25.179.80:3306/tb_blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
        username: liuk
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 20
        minIdle: 1

    thymeleaf:
        cache : true
        prefix : classpath:/templates/
        suffix : .html
        encoding : UTF-8
        content-type : text/html
        mode : HTML5
        check-template-location: true

    devtools:
        restart:
            #热部署生效
          enabled: true
            #设置重启的目录
            #additional-paths: src/main/java
            #classpath目录下的WEB-INF文件夹内容修改不重启
          exclude: classpath:/templates/**


mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.liuk.blog.model


pagehelper:
    helperDialect: mysql
    reasonable: true
    pageSizeZero: true
    params: count=countSql
    support-methods-arguments: true





